name: "Nix checks"
on:
  push:
    paths:
      - '**.nix'
      - .github/workflows/nix.yml
    branches:
      - main

jobs:
  checks:
    name: Lint
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GH_TOKEN }}
      - run: nix build
